config/routes.rb
Airports::Application.routes.draw do
  get "airports_with_weather/index"
  resources :airports

  root 'airports#index'

end

app/models/airport.rb
class Airport < ActiveRecord::Base
  require 'csv'
def self.to_csv(options = {})
  CSV.generate(options) do |csv|
    csv << column_names
    all.each do |airport|
      csv << airport.attributes.values_at(*column_names)
    end
  end
end
end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
  require 'csv'
  require 'crack/json'
  before_action :set_airport, only: [:show, :edit, :update, :destroy]

  # GET /airports
  # GET /airports.json
  def index
    @airports = Airport.paginate(:page => params[:page], :per_page => 30)
    
    respond_to do |format|
      format.html {  }
      format.csv { send_data @airports.to_csv }
      format.json { render json: @airports }
    end
  end

  # GET /airports/1
  # GET /airports/1.json
  def show
    lat = @airport.latitude_deg
    lng = @airport.longitude_deg
    
    @map_markers = Gmaps4rails.build_markers(@airport) do |airport,marker|
       marker.lat lat
       marker.lng lng
    end
  end

  # GET /airports/new
  def new
    @airport = Airport.new
  end

  # GET /airports/1/edit
  def edit
  end

  # POST /airports
  # POST /airports.json
  def create
    @airport = Airport.new(airport_params)

    respond_to do |format|
      if @airport.save
        format.html { redirect_to @airport, notice: 'Airport was successfully created.' }
        format.json { render action: 'show', status: :created, location: @airport }
      else
        format.html { render action: 'new' }
        format.json { render json: @airport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /airports/1
  # PATCH/PUT /airports/1.json
  def update
    respond_to do |format|
      if @airport.update(airport_params)
        format.html { redirect_to @airport, notice: 'Airport was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @airport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airports/1
  # DELETE /airports/1.json
  def destroy
    @airport.destroy
    respond_to do |format|
      format.html { redirect_to airports_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_airport
      @airport = Airport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def airport_params
      params.require(:airport).permit(:ident, :airport_type, :name, :latitude_deg, :longitude_deg, :elevation_ft, :continent, :iso_country, :iso_region, :municipality, :scheduled_service, :gps_code, :iata_code, :local_code, :home_link, :wikipedia_link, :keywords)
    end
end

app/controllers/airports_with_weather_controller.rb
class AirportsWithWeatherController < ApplicationController
  def index
    @airports = Airport.all(:limit => 25)
    @airports_with_weather = []
    @airports.each do |airport|
      @airports_with_weather << { name: airport.name,
                                  current_weather: get_current_weather(airport.latitude_deg, airport.longitude_deg)}
    end
    @airports_with_weather
  end

  private
  def get_current_weather(lat, long)
    response = RestClient.get "http://api.openweathermap.org/data/2.5/weather", :params => {:lat => lat, :lon => long}
    return ((JSON.parse(response.body)["main"]["temp"] - 273.15)* 1.8000 + 32.00).round(0)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/airports_helper.rb
module AirportsHelper
  def kelvin_to_fahrenheit(k)
    ((k - 273.15)* 1.8000 + 32.00).round(0)
  end
  
  def compass_point(bearing)
    points = %w[N NE E SE S SW W NW]
    seg_size = 360 / points.size
    points[((bearing + (seg_size / 2)) % 360) / seg_size]
  end
end

app/helpers/airports_with_weather_helper.rb
module AirportsWithWeatherHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/airports/_form.html.erb
<%= form_for(@airport) do |f| %>
  <% if @airport.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@airport.errors.count, "error") %> prohibited this airport from being saved:</h2>

      <ul>
      <% @airport.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ident %><br>
    <%= f.text_field :ident %>
  </div>
  <div class="field">
    <%= f.label :airport_type %><br>
    <%= f.text_field :airport_type %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :latitude_deg %><br>
    <%= f.text_field :latitude_deg %>
  </div>
  <div class="field">
    <%= f.label :longitude_deg %><br>
    <%= f.text_field :longitude_deg %>
  </div>
  <div class="field">
    <%= f.label :elevation_ft %><br>
    <%= f.number_field :elevation_ft %>
  </div>
  <div class="field">
    <%= f.label :continent %><br>
    <%= f.text_field :continent %>
  </div>
  <div class="field">
    <%= f.label :iso_country %><br>
    <%= f.text_field :iso_country %>
  </div>
  <div class="field">
    <%= f.label :iso_region %><br>
    <%= f.text_field :iso_region %>
  </div>
  <div class="field">
    <%= f.label :municipality %><br>
    <%= f.text_field :municipality %>
  </div>
  <div class="field">
    <%= f.label :scheduled_service %><br>
    <%= f.text_field :scheduled_service %>
  </div>
  <div class="field">
    <%= f.label :gps_code %><br>
    <%= f.text_field :gps_code %>
  </div>
  <div class="field">
    <%= f.label :iata_code %><br>
    <%= f.text_field :iata_code %>
  </div>
  <div class="field">
    <%= f.label :local_code %><br>
    <%= f.text_field :local_code %>
  </div>
  <div class="field">
    <%= f.label :home_link %><br>
    <%= f.text_field :home_link %>
  </div>
  <div class="field">
    <%= f.label :wikipedia_link %><br>
    <%= f.text_field :wikipedia_link %>
  </div>
  <div class="field">
    <%= f.label :keywords %><br>
    <%= f.text_field :keywords %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/airports/edit.html.erb
<h1>Editing airport</h1>

<%= render 'form' %>

<%= link_to 'Show', @airport %> |
<%= link_to 'Back', airports_path %>

app/views/airports/index.html.erb
<h1>Listing airports</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Continent</th>
      <th>Iso country</th>
      <th>Iso region</th>
      <th>Municipality</th>
      <th>Scheduled service</th>
    </tr>
  </thead>

  <tbody id='airports'>
  </tbody>
</table>

<div class="col-lg-4">
</div>

<div class="col-lg-4">
  <%= image_tag("loader.gif", :id => 'next_page_spinner') %>
</div>

<div class="col-lg-4">
</div>

app/views/airports/new.html.erb
<h1>New airport</h1>

<%= render 'form' %>

<%= link_to 'Back', airports_path %>

app/views/airports/show.html.erb
<h1><%= @airport.name %></h1>
<p id="notice"><%= notice %></p>
<div class="row">
<div class="col-md-9">
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<div class="col-md-3" id="weather-data">
  <h3>Weather</h3>
  <%= image_tag("loader.gif", :id => 'next_page_spinner') %>
</div>

</div>
<%= link_to 'Back', airports_path %>

<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @map_markers.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

<script>
  var url =<%=raw "'http://api.openweathermap.org/data/2.5/weather?lat=#{@airport.latitude_deg}&lon=#{@airport.longitude_deg}';" %>
  window.getWeather(url);
</script>

app/views/airports_with_weather/index.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Current Temp</th>
  </tr>
  <% @airports_with_weather.each do |airport| %>
    <tr>
      <td><%=airport[:name] %></td>
      <td><%=airport[:current_weather] %></td>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Airports</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container content" role="main">
    <div class="row">
      <div class="col-md-12">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>